use std::collections::HashMap;
use std::env;
use std::fmt::Write;
use std::fs;
use std::path::Path;

fn main() {
    // Tell Cargo to re-run this build script if the prompts directory changes
    println!("cargo:rerun-if-changed=../builtin/prompts");
    // Tell Cargo to re-run this build script if the workflows directory changes
    println!("cargo:rerun-if-changed=../builtin/workflows");
    // Tell Cargo to re-run this build script if the tool descriptions change
    println!("cargo:rerun-if-changed=src/mcp/tools");

    let out_dir = env::var("OUT_DIR").unwrap();

    // Generate builtin prompts
    generate_builtin_prompts(&out_dir);

    // Generate builtin workflows
    generate_builtin_workflows(&out_dir);

    // Generate tool descriptions
    generate_tool_descriptions(&out_dir);
}

fn generate_builtin_prompts(out_dir: &str) {
    let dest_path = Path::new(&out_dir).join("builtin_prompts.rs");

    // Get the manifest directory (where Cargo.toml is located)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let builtin_dir = Path::new(&manifest_dir).join("../builtin/prompts");

    let mut code = String::new();
    code.push_str("// Auto-generated builtin prompts - do not edit manually\n");
    code.push_str("// Generated by build.rs from builtin/prompts directory\n\n");
    code.push_str("/// Get all built-in prompts as a vector of (name, content) tuples\n");
    code.push_str("pub fn get_builtin_prompts() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");

    if builtin_dir.exists() {
        collect_prompts(&builtin_dir, "", &mut code);
    }

    code.push_str("    ]\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();
}

fn generate_builtin_workflows(out_dir: &str) {
    let dest_path = Path::new(&out_dir).join("builtin_workflows.rs");

    // Get the manifest directory (where Cargo.toml is located)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let builtin_dir = Path::new(&manifest_dir).join("../builtin/workflows");

    let mut code = String::new();
    code.push_str("// Auto-generated builtin workflows - do not edit manually\n");
    code.push_str("// Generated by build.rs from builtin/workflows directory\n\n");
    code.push_str("/// Get all built-in workflows as a vector of (name, content) tuples\n");
    code.push_str("pub fn get_builtin_workflows() -> Vec<(&'static str, &'static str)> {\n");
    code.push_str("    vec![\n");

    if builtin_dir.exists() {
        collect_workflows(&builtin_dir, "", &mut code);
    }

    code.push_str("    ]\n");
    code.push_str("}\n");

    fs::write(&dest_path, code).unwrap();
}

fn collect_prompts(dir: &Path, prefix: &str, code: &mut String) {
    if let Ok(entries) = fs::read_dir(dir) {
        let mut entries: Vec<_> = entries.collect();
        entries.sort_by_key(|entry| entry.as_ref().unwrap().path());

        for entry in entries.into_iter().flatten() {
            let path = entry.path();
            let name = path.file_name().unwrap().to_string_lossy();

            if path.is_dir() {
                // Skip the workflows directory as these are workflow definitions, not regular prompts
                if name == "workflows" {
                    continue;
                }
                // Recursively collect from subdirectories
                let new_prefix = if prefix.is_empty() {
                    name.to_string()
                } else {
                    format!("{prefix}/{name}")
                };
                collect_prompts(&path, &new_prefix, code);
            } else if name.ends_with(".md") || name.ends_with(".liquid") {
                // Generate the prompt name
                let prompt_name = if prefix.is_empty() {
                    name.strip_suffix(".md")
                        .or_else(|| name.strip_suffix(".liquid"))
                        .unwrap_or(&name)
                        .to_string()
                } else {
                    format!(
                        "{}/{}",
                        prefix,
                        name.strip_suffix(".md")
                            .or_else(|| name.strip_suffix(".liquid"))
                            .unwrap_or(&name)
                    )
                };

                // Read the file content at build time and embed it as a string literal
                if let Ok(content) = fs::read_to_string(&path) {
                    writeln!(code, "        (\"{prompt_name}\", r#\"{content}\"#),").unwrap();
                }
            }
        }
    }
}

fn collect_workflows(dir: &Path, prefix: &str, code: &mut String) {
    if let Ok(entries) = fs::read_dir(dir) {
        let mut entries: Vec<_> = entries.collect();
        entries.sort_by_key(|entry| entry.as_ref().unwrap().path());

        for entry in entries.into_iter().flatten() {
            let path = entry.path();
            let name = path.file_name().unwrap().to_string_lossy();

            if path.is_dir() {
                // Recursively collect from subdirectories
                let new_prefix = if prefix.is_empty() {
                    name.to_string()
                } else {
                    format!("{prefix}/{name}")
                };
                collect_workflows(&path, &new_prefix, code);
            } else if name.ends_with(".md") {
                // Generate the workflow name
                let workflow_name = if prefix.is_empty() {
                    name.strip_suffix(".md").unwrap_or(&name).to_string()
                } else {
                    format!("{}/{}", prefix, name.strip_suffix(".md").unwrap_or(&name))
                };

                // Read the file content at build time and embed it as a string literal
                if let Ok(content) = fs::read_to_string(&path) {
                    writeln!(code, "        (\"{workflow_name}\", r#\"{content}\"#),").unwrap();
                }
            }
        }
    }
}

fn generate_tool_descriptions(out_dir: &str) {
    let dest_path = Path::new(&out_dir).join("tool_descriptions.rs");

    // Get the manifest directory (where Cargo.toml is located)
    let manifest_dir = env::var("CARGO_MANIFEST_DIR").unwrap();
    let tools_dir = Path::new(&manifest_dir).join("src/mcp/tools");

    let mut descriptions = HashMap::new();

    if tools_dir.exists() {
        collect_tool_descriptions(&tools_dir, "", &mut descriptions);
    }

    generate_tool_descriptions_code(&descriptions, &dest_path);
}

fn collect_tool_descriptions(
    dir: &Path,
    prefix: &str,
    descriptions: &mut HashMap<String, String>,
) {
    if let Ok(entries) = fs::read_dir(dir) {
        let mut entries: Vec<_> = entries.collect();
        entries.sort_by_key(|entry| entry.as_ref().unwrap().path());

        for entry in entries.into_iter().flatten() {
            let path = entry.path();
            let name = path.file_name().unwrap().to_string_lossy();

            if path.is_dir() {
                let dir_name = name.to_string();
                let new_prefix = if prefix.is_empty() {
                    dir_name.clone()
                } else {
                    format!("{}_{}", prefix, dir_name)
                };

                // Check for description.md in this directory
                let desc_file = path.join("description.md");
                if desc_file.exists() {
                    if let Ok(content) = fs::read_to_string(&desc_file) {
                        // Validate the description content
                        if let Err(e) = validate_tool_description(&content, &new_prefix) {
                            panic!("Tool description validation failed for {}: {}", new_prefix, e);
                        }
                        descriptions.insert(new_prefix.clone(), content);
                        println!("cargo:rerun-if-changed={}", desc_file.display());
                    }
                }

                // Recurse into subdirectories
                collect_tool_descriptions(&path, &new_prefix, descriptions);
            }
        }
    }
}

fn generate_tool_descriptions_code(descriptions: &HashMap<String, String>, dest_path: &Path) {
    let mut code = String::new();
    code.push_str("// Auto-generated tool descriptions - do not edit manually\n");
    code.push_str("// Generated by build.rs from src/mcp/tools directory\n\n");
    code.push_str("/// Get all tool descriptions as a HashMap mapping tool paths to content\n");
    code.push_str("pub fn get_tool_descriptions() -> std::collections::HashMap<&'static str, &'static str> {\n");
    code.push_str("    let mut map = std::collections::HashMap::new();\n");

    // Sort keys for consistent output
    let mut sorted_descriptions: Vec<_> = descriptions.iter().collect();
    sorted_descriptions.sort_by_key(|(k, _)| *k);

    for (tool_path, description) in sorted_descriptions {
        writeln!(code, "    map.insert({:?}, {:?});", tool_path, description).unwrap();
    }

    code.push_str("    map\n");
    code.push_str("}\n");

    fs::write(dest_path, code).unwrap();
}

fn validate_tool_description(content: &str, tool_path: &str) -> Result<(), String> {
    // Basic validation
    if content.trim().is_empty() {
        return Err(format!("Description for {} is empty", tool_path));
    }

    // Check for basic structure - should have some content
    if content.len() < 10 {
        return Err(format!("Description for {} is too short", tool_path));
    }

    // Optional: Check for Parameters section if needed
    // This is relaxed validation - tools can have different formats
    
    Ok(())
}
