//! Task commands

mod add;
mod archive;
mod assign;
mod complete;
mod copy;
mod cut;
mod delete;
pub mod embedding_cache;
mod get;
mod list;
mod mv;
mod next;
mod paste;
mod search;
mod shared;
mod tag;
mod tags;
mod unassign;
mod untag;
mod update;

pub use add::AddTask;
pub use archive::{ArchiveTask, ListArchived, UnarchiveTask};
pub use assign::AssignTask;
pub use complete::CompleteTask;
pub use copy::CopyTask;
pub use cut::CutTask;
pub use delete::DeleteTask;
pub use embedding_cache::{content_hash, task_embedding_text, EmbeddingCache};
pub use get::GetTask;
pub use list::{ListTasks, MAX_PAGE_SIZE};
pub use mv::MoveTask;
pub use next::NextTask;
pub use paste::PasteTask;
pub use search::SearchTasks;
pub use tag::TagTask;
pub use unassign::UnassignTask;
pub use untag::UntagTask;
pub use update::UpdateTask;
