//! Schema-driven CLI generation.
//!
//! Builds a clap `Command` tree from a tool's MCP schema (the output of
//! [`crate::schema::generate_mcp_schema`]). The generator reads the `op` enum's
//! `verb noun` values and `x-operation-schemas` to produce a `noun → verb → args`
//! command tree where each verb's arguments are scoped to exactly the parameters
//! that operation accepts — not the global union of every operation's parameters.
//!
//! This engine is tool-agnostic: it consumes whatever full schema it is handed,
//! so every CLI built on the `Operation` trait (kanban-cli, sah, code-context-cli,
//! shelltool-cli) can share it.
//!
//! The two public entry points are:
//! - [`build_commands_from_schema`] — schema → clap command tree.
//! - [`extract_noun_verb_arguments`] — clap matches → `{ "op": "verb noun", ...args }`.

use crate::forgiving::expand_list_entry;
use clap::{Arg, ArgAction, Command};
use once_cell::sync::Lazy;
use serde_json::Value;
use std::collections::{HashMap, HashSet};
use std::sync::Mutex;

/// The synthetic field name carrying the `"verb noun"` op string.
///
/// This key is generated by the engine (not a real schema property) and is read
/// and written at several sites; naming it once keeps those sites in lockstep.
const OP_FIELD: &str = "op";

/// JSON Schema `type` token for a boolean property.
///
/// The JSON Schema type names form a small closed vocabulary that the engine
/// matches on at several sites (type probing, arg-type resolution, value
/// extraction); naming each token once keeps those sites in lockstep and the
/// vocabulary in a single place.
const TYPE_BOOLEAN: &str = "boolean";

/// JSON Schema `type` token for the null type (used in nullable unions).
const TYPE_NULL: &str = "null";

/// JSON Schema `type` token for an array property.
const TYPE_ARRAY: &str = "array";

/// JSON Schema `type` token for an integer property.
const TYPE_INTEGER: &str = "integer";

/// JSON Schema `type` token for a (floating-point) number property.
const TYPE_NUMBER: &str = "number";

// ---------------------------------------------------------------------------
// String interning (clap requires 'static lifetimes)
// ---------------------------------------------------------------------------

/// Cache of interned strings handed out as `&'static str` to clap.
static STRING_CACHE: Lazy<Mutex<HashSet<&'static str>>> = Lazy::new(|| Mutex::new(HashSet::new()));

/// Intern a string, returning a `&'static str` clap can hold.
///
/// clap's builder API requires `'static` names/help text. Schema-derived
/// strings are owned at runtime, so we leak them once and reuse the leaked
/// reference for any equal string thereafter (bounded by the schema size).
fn intern(s: String) -> &'static str {
    let mut cache = STRING_CACHE.lock().unwrap();
    if let Some(&cached) = cache.get(s.as_str()) {
        return cached;
    }
    let leaked: &'static str = Box::leak(s.into_boxed_str());
    cache.insert(leaked);
    leaked
}

// ---------------------------------------------------------------------------
// Schema helpers
// ---------------------------------------------------------------------------

/// Return `true` if a property schema declares `type_name`, handling both
/// a plain string `type` and a `type` array (e.g. `["boolean", "null"]`).
fn schema_has_type(schema: &Value, type_name: &str) -> bool {
    match schema.get("type") {
        Some(Value::String(t)) => t.as_str() == type_name,
        Some(Value::Array(types)) => types.iter().any(|t| t.as_str() == Some(type_name)),
        _ => false,
    }
}

/// Return the primary (non-null) JSON Schema type of a property, if any.
///
/// For a `type` array such as `["string", "null"]` the first non-`null`
/// entry wins; for a plain string `type` that string is returned.
fn primary_type(schema: &Value) -> Option<&str> {
    match schema.get("type") {
        Some(Value::String(t)) => Some(t.as_str()),
        Some(Value::Array(types)) => types
            .iter()
            .find_map(|t| t.as_str().filter(|s| *s != TYPE_NULL)),
        _ => None,
    }
}

// ---------------------------------------------------------------------------
// Build clap commands from schema
// ---------------------------------------------------------------------------

/// Build the `noun → verb` command tree from a tool's MCP schema.
///
/// Uses `x-operation-schemas` to scope each verb's args to only the parameters
/// that operation actually accepts (so required flags are correct per op, not
/// the global union). Falls back to the global `properties` block when a schema
/// has no `x-operation-schemas`.
///
/// # Arguments
///
/// * `schema` - A full MCP schema as produced by [`crate::schema::generate_mcp_schema`].
///
/// # Returns
///
/// A list of top-level clap [`Command`]s, one per noun, each with its verbs as
/// subcommands. The list is sorted by noun name. Returns an empty vec when the
/// schema has no `properties.op.enum`.
pub fn build_commands_from_schema(schema: &Value) -> Vec<Command> {
    // Per-op arg maps (keyed by op string, e.g. "init board"); empty when the
    // schema carries no x-operation-schemas.
    let op_args = build_op_args(schema);

    // Fall back to the global schema args only when no per-op schemas exist.
    let fallback_args = if op_args.is_empty() {
        precompute_args(schema)
    } else {
        Vec::new()
    };

    // Parse the op enum into the "verb noun" values; absent -> no commands.
    let op_values = match schema
        .get("properties")
        .and_then(|p| p.get(OP_FIELD))
        .and_then(|op| op.get("enum"))
        .and_then(|e| e.as_array())
    {
        Some(arr) => arr,
        None => return Vec::new(),
    };

    let mut commands: Vec<Command> = group_verbs_by_noun(op_values)
        .into_iter()
        .map(|(noun, verbs)| build_noun_command(&noun, &verbs, &op_args, &fallback_args))
        .collect();
    commands.sort_by(|a, b| a.get_name().cmp(b.get_name()));
    commands
}

/// Build the per-operation arg map from a schema's `x-operation-schemas`.
///
/// Each entry is keyed by the op `title` (e.g. `"init board"`) and carries that
/// operation's `description` plus its precomputed [`ArgMeta`] (so required flags
/// are scoped to exactly that op, not the global union). Returns an empty map
/// when the schema has no `x-operation-schemas` array.
fn build_op_args(schema: &Value) -> HashMap<String, (String, Vec<ArgMeta>)> {
    let mut op_args: HashMap<String, (String, Vec<ArgMeta>)> = HashMap::new();
    let Some(op_schemas) = schema.get("x-operation-schemas").and_then(|v| v.as_array()) else {
        return op_args;
    };
    for op_schema in op_schemas {
        let Some(title) = op_schema.get("title").and_then(|t| t.as_str()) else {
            continue;
        };
        let desc = op_schema
            .get("description")
            .and_then(|d| d.as_str())
            .unwrap_or("")
            .to_string();
        op_args.insert(title.to_string(), (desc, precompute_args(op_schema)));
    }
    op_args
}

/// Group `"verb noun"` op enum values by noun.
///
/// Each op string is split on the first space into `verb` and `noun`; values that
/// are not a `"verb noun"` pair are skipped. Returns a map of noun to its
/// `(verb, op_string)` pairs, where `op_string` is the original value used to look
/// up per-op args.
fn group_verbs_by_noun(op_values: &[Value]) -> HashMap<String, Vec<(String, String)>> {
    let mut noun_groups: HashMap<String, Vec<(String, String)>> = HashMap::new();
    for op_val in op_values {
        let Some(op_str) = op_val.as_str() else {
            continue;
        };
        let parts: Vec<&str> = op_str.splitn(2, ' ').collect();
        if parts.len() == 2 {
            noun_groups
                .entry(parts[1].to_string())
                .or_default()
                .push((parts[0].to_string(), op_str.to_string()));
        }
    }
    noun_groups
}

/// Build a single noun command with its verbs as sorted subcommands.
///
/// # Arguments
///
/// * `noun` - The noun name (e.g. `"board"`).
/// * `verbs` - `(verb, op_string)` pairs for this noun.
/// * `op_args` - Per-op precomputed args keyed by op string.
/// * `fallback_args` - Args to use when an op has no per-op schema.
fn build_noun_command(
    noun: &str,
    verbs: &[(String, String)],
    op_args: &HashMap<String, (String, Vec<ArgMeta>)>,
    fallback_args: &[ArgMeta],
) -> Command {
    let mut cmd =
        Command::new(intern(noun.to_string())).about(intern(format!("{} operations", noun)));

    let mut verb_cmds: Vec<Command> = verbs
        .iter()
        .map(|(verb, op_str)| build_verb_command(verb, op_str, op_args, fallback_args))
        .collect();
    verb_cmds.sort_by(|a, b| a.get_name().cmp(b.get_name()));

    for verb_cmd in verb_cmds {
        cmd = cmd.subcommand(verb_cmd);
    }
    cmd
}

/// Build a single verb subcommand, scoping its args to that operation.
///
/// Uses the per-op args from `op_args` when present (keyed by `op_str`),
/// otherwise the `fallback_args`. The synthetic `op` parameter is skipped
/// because it is supplied by the noun-verb path, not a flag.
///
/// # Arguments
///
/// * `verb` - The verb name (e.g. `"init"`).
/// * `op_str` - The full op string (e.g. `"init board"`) used as the arg-map key.
/// * `op_args` - Per-op precomputed args keyed by op string.
/// * `fallback_args` - Args to use when this op has no per-op schema.
fn build_verb_command(
    verb: &str,
    op_str: &str,
    op_args: &HashMap<String, (String, Vec<ArgMeta>)>,
    fallback_args: &[ArgMeta],
) -> Command {
    // Use per-operation args if available, otherwise fall back to global
    let (about, args) = if let Some((desc, per_op_args)) = op_args.get(op_str) {
        (desc.as_str(), per_op_args.as_slice())
    } else {
        ("", fallback_args)
    };

    let about_str = if about.is_empty() {
        format!("{} operation", verb)
    } else {
        about.to_string()
    };

    let mut cmd = Command::new(intern(verb.to_string())).about(intern(about_str));

    for arg in args {
        if arg.name == OP_FIELD {
            continue;
        }
        cmd = cmd.arg(build_clap_arg(arg));
    }
    cmd
}

// ---------------------------------------------------------------------------
// Arg metadata extraction from JSON schema
// ---------------------------------------------------------------------------

/// Precomputed clap argument metadata derived from one JSON schema property.
#[derive(Debug, Clone)]
struct ArgMeta {
    /// The parameter name (becomes the clap arg id and `--long` flag).
    name: String,
    /// Help text from the property's `description`, if any.
    help: Option<String>,
    /// Whether the parameter is required for this operation.
    is_required: bool,
    /// The clap value type to configure for this argument.
    arg_type: ArgMetaType,
    /// Default value from the property's `default`, if any.
    default_value: Option<String>,
    /// Allowed values from the property's `enum`, if any.
    possible_values: Option<Vec<String>>,
}

/// The clap-relevant value type of an argument, derived from the JSON Schema type.
#[derive(Debug, Clone)]
enum ArgMetaType {
    /// A plain string value.
    String,
    /// A 64-bit signed integer.
    Integer,
    /// A 64-bit float.
    Float,
    /// A flag (`--flag` with no value, sets `true`).
    Boolean,
    /// A nullable boolean accepting an explicit `true`/`false` value.
    NullableBoolean,
    /// A repeatable string value collected into an array.
    Array,
}

/// Parse a schema's `required` list into a set of required parameter names.
///
/// Returns an empty set when there is no `required` array.
fn required_param_names(schema: &Value) -> HashSet<String> {
    schema
        .get("required")
        .and_then(|r| r.as_array())
        .map(|arr| {
            arr.iter()
                .filter_map(|v| v.as_str())
                .map(|s| s.to_string())
                .collect()
        })
        .unwrap_or_default()
}

/// Resolve the clap value type for a single JSON schema property.
///
/// A property typed `["boolean", "null"]` becomes [`ArgMetaType::NullableBoolean`];
/// otherwise the primary (non-null) JSON Schema type selects the variant, with
/// any unknown or absent type falling back to [`ArgMetaType::String`].
fn resolve_arg_type(prop_schema: &Value) -> ArgMetaType {
    if schema_has_type(prop_schema, TYPE_BOOLEAN) && schema_has_type(prop_schema, TYPE_NULL) {
        return ArgMetaType::NullableBoolean;
    }
    match primary_type(prop_schema) {
        Some(TYPE_BOOLEAN) => ArgMetaType::Boolean,
        Some(TYPE_INTEGER) => ArgMetaType::Integer,
        Some(TYPE_NUMBER) => ArgMetaType::Float,
        Some(TYPE_ARRAY) => ArgMetaType::Array,
        _ => ArgMetaType::String,
    }
}

/// Convert a schema (an op schema or the global schema) into ordered [`ArgMeta`].
///
/// Reads `properties` and the `required` list. Array parameters are never marked
/// required (they default to empty in CLI context) and the synthetic `op`
/// parameter is never required (it is set by the noun-verb path). The clap value
/// type for each property is resolved by [`resolve_arg_type`].
fn precompute_args(schema: &Value) -> Vec<ArgMeta> {
    let properties = match schema.get("properties").and_then(|p| p.as_object()) {
        Some(props) => props,
        None => return Vec::new(),
    };

    let required = required_param_names(schema);

    properties
        .iter()
        .map(|(name, prop_schema)| {
            // In CLI context, arrays default to empty so never require them.
            // Also skip requiring the op field — it's set by the noun-verb path.
            let is_required = required.contains(name)
                && !matches!(primary_type(prop_schema), Some(TYPE_ARRAY))
                && name != OP_FIELD;

            ArgMeta {
                name: name.clone(),
                help: prop_schema
                    .get("description")
                    .and_then(|v| v.as_str())
                    .map(String::from),
                is_required,
                arg_type: resolve_arg_type(prop_schema),
                default_value: prop_schema
                    .get("default")
                    .and_then(|v| v.as_str())
                    .map(String::from),
                possible_values: prop_schema
                    .get("enum")
                    .and_then(|v| v.as_array())
                    .map(|arr| {
                        arr.iter()
                            .filter_map(|v| v.as_str().map(String::from))
                            .collect()
                    }),
            }
        })
        .collect()
}

/// Build a clap [`Arg`] from precomputed [`ArgMeta`].
///
/// Maps the arg type to the right clap value parser / action, wires up
/// required-ness, help, default value, and `enum`-derived possible values.
fn build_clap_arg(meta: &ArgMeta) -> Arg {
    let name_static = intern(meta.name.clone());
    let mut arg = Arg::new(name_static).long(name_static);

    if meta.is_required {
        arg = arg.required(true);
    }
    if let Some(ref help) = meta.help {
        arg = arg.help(intern(help.clone()));
    }
    if let Some(ref default) = meta.default_value {
        arg = arg.default_value(intern(default.clone()));
    }
    if let Some(ref values) = meta.possible_values {
        let strs: Vec<&'static str> = values.iter().map(|s| intern(s.clone())).collect();
        arg = arg.value_parser(clap::builder::PossibleValuesParser::new(strs));
    }

    arg = match meta.arg_type {
        ArgMetaType::Boolean => arg.action(ArgAction::SetTrue),
        ArgMetaType::NullableBoolean => arg
            .value_parser(clap::builder::PossibleValuesParser::new(["true", "false"]))
            .value_name("BOOL"),
        ArgMetaType::Integer => {
            let mut a = arg.value_parser(clap::value_parser!(i64));
            if !meta.is_required {
                a = a.value_name("NUMBER");
            }
            a
        }
        ArgMetaType::Float => {
            let mut a = arg.value_parser(clap::value_parser!(f64));
            if !meta.is_required {
                a = a.value_name("NUMBER");
            }
            a
        }
        ArgMetaType::Array => {
            let mut a = arg.action(ArgAction::Append);
            if !meta.is_required {
                a = a.value_name("VALUE");
            }
            a
        }
        ArgMetaType::String => {
            if !meta.is_required {
                arg.value_name("TEXT")
            } else {
                arg
            }
        }
    };

    arg
}

// ---------------------------------------------------------------------------
// Extract arguments from clap matches
// ---------------------------------------------------------------------------

/// Error returned when clap matches cannot be resolved to a `verb noun` op.
///
/// This enum is `#[non_exhaustive]`: it is part of this crate's public API, shared
/// by every CLI built on the `Operation` trait, so new variants may be added in
/// future without a breaking change. Downstream `match`es must include a wildcard
/// arm. (Within this crate `#[non_exhaustive]` does not force a wildcard, so the
/// engine's own exhaustive matches remain valid.)
#[derive(Debug, thiserror::Error)]
#[non_exhaustive]
pub enum CliExtractError {
    /// No noun subcommand was present in the matches.
    #[error("no noun specified")]
    MissingNoun,
    /// A noun was given but it had no verb subcommand. Carries the noun name.
    #[error("no verb specified for '{0}'")]
    MissingVerb(String),
    /// A float argument was non-finite (`inf`, `-inf`, or `nan`). clap accepts
    /// these but JSON cannot represent them, so they are rejected rather than
    /// silently dropped. Carries the offending argument name.
    #[error("argument '{name}' is not a finite number")]
    NonFiniteFloat {
        /// The name of the argument that received a non-finite value.
        name: String,
    },
}

/// Extract noun-verb arguments from matched clap args.
///
/// Navigates the `noun → verb` subcommand tree and builds a JSON object with
/// `"op": "verb noun"` plus all matched arguments, suitable for handing to an
/// [`crate::processor::OperationProcessor`].
///
/// # Arguments
///
/// * `matches` - The top-level clap matches (with the noun as the subcommand).
/// * `schema` - The same full schema used to build the commands; its `properties`
///   drive which arguments are read and how they are typed.
///
/// # Errors
///
/// Returns [`CliExtractError::MissingNoun`] when no noun was given, or
/// [`CliExtractError::MissingVerb`] when a noun was given without a verb.
pub fn extract_noun_verb_arguments(
    matches: &clap::ArgMatches,
    schema: &Value,
) -> Result<serde_json::Map<String, Value>, CliExtractError> {
    match matches.subcommand() {
        Some((noun, noun_matches)) => match noun_matches.subcommand() {
            Some((verb, verb_matches)) => {
                let op_string = format!("{} {}", verb, noun);
                build_arguments_from_matches(verb_matches, &op_string, schema)
            }
            None => Err(CliExtractError::MissingVerb(noun.to_string())),
        },
        None => Err(CliExtractError::MissingNoun),
    }
}

/// Assemble the `{ "op": ..., ...args }` JSON object from a verb's clap matches.
///
/// Iterates the schema's global `properties`, pulling each present value out of
/// the matches via [`extract_value_from_matches`]. Arguments not defined on this
/// particular verb are silently skipped (per-operation scoping).
///
/// # Arguments
///
/// * `matches` - The verb-level clap matches.
/// * `op_string` - The `"verb noun"` op string to record under `"op"`.
/// * `schema` - The full schema providing the property type information.
fn build_arguments_from_matches(
    matches: &clap::ArgMatches,
    op_string: &str,
    schema: &Value,
) -> Result<serde_json::Map<String, Value>, CliExtractError> {
    let mut arguments = serde_json::Map::new();

    if !op_string.is_empty() {
        arguments.insert(OP_FIELD.to_string(), Value::String(op_string.to_string()));
    }

    if let Some(properties) = schema.get("properties").and_then(|p| p.as_object()) {
        for (prop_name, prop_schema) in properties {
            if prop_name == OP_FIELD {
                continue;
            }
            if let Some(value) = extract_value_from_matches(matches, prop_name, prop_schema)? {
                arguments.insert(prop_name.clone(), value);
            }
        }
    }

    Ok(arguments)
}

/// Extract one typed JSON value for `name` from clap matches, if present.
///
/// Returns `Ok(None)` when the argument is not defined on this command (per-op
/// scoping) or was not supplied. The JSON type is chosen from the property's
/// schema `type`:
/// - a nullable boolean (`["boolean", "null"]`) is built as a value-taking arg,
///   so its parsed `"true"`/`"false"` string is read and converted to a bool —
///   this is checked before the plain-boolean branch because [`primary_type`]
///   also reports `"boolean"` for the union;
/// - a plain boolean (`"boolean"`) is a flag, emitting `true` only when set;
/// - an array collects every occurrence of its repeatable flag, and each
///   occurrence goes through [`expand_list_entry`], so one
///   `--tags '["red","blue"]'` means the same two entries as two `--tags`
///   flags — a shell argument carries one string, which is why the JSON-array
///   form exists at all;
/// - empty arrays collapse to `Ok(None)`.
///
/// # Errors
///
/// Returns [`CliExtractError::NonFiniteFloat`] when a `number` argument parsed to
/// a non-finite value (`inf`/`-inf`/`nan`), which JSON cannot represent.
fn extract_value_from_matches(
    matches: &clap::ArgMatches,
    name: &str,
    schema: &Value,
) -> Result<Option<Value>, CliExtractError> {
    // Skip args not defined in this command (per-operation scoping)
    if !matches.try_contains_id(name).unwrap_or(false) {
        return Ok(None);
    }

    // A nullable boolean is built as a value arg (not a SetTrue flag), so it must
    // be read as its parsed string value — `get_flag` would panic here. Check it
    // before the plain-boolean branch since `primary_type` reports "boolean" too.
    if schema_has_type(schema, TYPE_BOOLEAN) && schema_has_type(schema, TYPE_NULL) {
        return Ok(matches
            .get_one::<String>(name)
            .and_then(|v| v.parse::<bool>().ok())
            .map(Value::Bool));
    }

    let value = match primary_type(schema) {
        Some(TYPE_BOOLEAN) => matches.get_flag(name).then_some(Value::Bool(true)),
        Some(TYPE_INTEGER) => matches
            .get_one::<i64>(name)
            .map(|v| Value::Number((*v).into())),
        Some(TYPE_NUMBER) => match matches.get_one::<f64>(name) {
            Some(v) => Some(Value::Number(serde_json::Number::from_f64(*v).ok_or_else(
                || CliExtractError::NonFiniteFloat {
                    name: name.to_string(),
                },
            )?)),
            None => None,
        },
        Some(TYPE_ARRAY) => {
            let values: Vec<String> = matches
                .get_many::<String>(name)
                .map(|v| v.flat_map(|raw| expand_list_entry(raw)).collect())
                .unwrap_or_default();
            if values.is_empty() {
                None
            } else {
                Some(Value::Array(
                    values.into_iter().map(Value::String).collect(),
                ))
            }
        }
        _ => matches
            .get_one::<String>(name)
            .map(|v| Value::String(v.clone())),
    };

    Ok(value)
}

#[cfg(any(test, feature = "test-helpers"))]
pub mod test_support {
    //! Reusable test helpers for CLIs built on the shared generator.
    //!
    //! Each consuming CLI's test module previously re-declared the same
    //! "build the command tree from a schema, parse an argv, extract the
    //! argument map" sequence. This helper lives next to
    //! [`build_commands_from_schema`]/[`extract_noun_verb_arguments`] so the
    //! round-trip is exercised through one shared path.

    use super::{build_commands_from_schema, extract_noun_verb_arguments};
    use clap::Command;
    use serde_json::{Map, Value};
    use std::collections::HashSet;

    /// Build the command tree from `schema`, parse `argv` against it, and
    /// extract the `{ "op": "verb noun", ...args }` argument map.
    ///
    /// `root_name` is the binary name the synthetic root command uses (e.g.
    /// `"code-context"`); it only affects clap's error messages, not the
    /// extracted args. Panics if `argv` does not parse or the matches cannot be
    /// resolved to an op — appropriate for test code that controls both.
    pub fn parse_argv(
        root_name: &'static str,
        schema: &Value,
        argv: &[&str],
    ) -> Map<String, Value> {
        let mut cmd = Command::new(root_name);
        for subcmd in build_commands_from_schema(schema) {
            cmd = cmd.subcommand(subcmd);
        }
        let matches = cmd
            .try_get_matches_from(argv)
            .expect("argv should parse against the generated command tree");
        extract_noun_verb_arguments(&matches, schema)
            .expect("matches should resolve to a noun/verb op")
    }

    /// Collect the `"verb noun"` op strings reachable through a `noun → verb`
    /// command tree.
    ///
    /// `nouns` is the set of top-level noun commands (either the `Vec<Command>`
    /// returned by [`build_commands_from_schema`], or the `get_subcommands()` of
    /// an assembled root). For each noun, every child verb yields the op string
    /// `"<verb> <noun>"`, matching [`crate::Operation::op_string`].
    ///
    /// Every CLI's command-tree coverage test previously open-coded this nested
    /// loop; sharing it here keeps the noun/verb convention in one place so the
    /// coverage tests cannot drift apart.
    pub fn collect_verb_noun_pairs<'a, I>(nouns: I) -> HashSet<String>
    where
        I: IntoIterator<Item = &'a Command>,
    {
        let mut pairs = HashSet::new();
        for noun_cmd in nouns {
            let noun = noun_cmd.get_name();
            for verb_cmd in noun_cmd.get_subcommands() {
                pairs.insert(format!("{} {}", verb_cmd.get_name(), noun));
            }
        }
        pairs
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::schema::{generate_mcp_schema, SchemaConfig};
    use crate::test_support::{
        MockAddColumn, MockAddTag, MockAddTask, MockGetBoard, MockInitBoard, MockListTasks,
        MockUpdateBoard,
    };
    use crate::Operation;
    use clap::Command;
    use serde_json::{json, Value};

    /// Build a mock multi-noun schema for testing the generator.
    ///
    /// Uses the shared [`crate::test_support`] mock operations:
    /// board {init, get, update}, task {add}, column {add}, tag {add}.
    fn mock_schema() -> Value {
        let ops: Vec<&dyn Operation> = vec![
            &MockInitBoard,
            &MockGetBoard,
            &MockUpdateBoard,
            &MockAddTask,
            &MockAddColumn,
            &MockAddTag,
        ];
        generate_mcp_schema(&ops, SchemaConfig::new("Mock operations"))
    }

    #[test]
    fn resolve_arg_type_maps_json_schema_types() {
        assert!(matches!(
            resolve_arg_type(&json!({"type": "string"})),
            ArgMetaType::String
        ));
        assert!(matches!(
            resolve_arg_type(&json!({"type": "integer"})),
            ArgMetaType::Integer
        ));
        assert!(matches!(
            resolve_arg_type(&json!({"type": "number"})),
            ArgMetaType::Float
        ));
        assert!(matches!(
            resolve_arg_type(&json!({"type": "boolean"})),
            ArgMetaType::Boolean
        ));
        assert!(matches!(
            resolve_arg_type(&json!({"type": "array"})),
            ArgMetaType::Array
        ));
        // A ["boolean", "null"] union resolves to NullableBoolean, not Boolean.
        assert!(matches!(
            resolve_arg_type(&json!({"type": ["boolean", "null"]})),
            ArgMetaType::NullableBoolean
        ));
        // Unknown/absent type falls back to String.
        assert!(matches!(resolve_arg_type(&json!({})), ArgMetaType::String));
    }

    #[test]
    fn build_commands_produces_noun_verb_tree() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let names: Vec<&str> = commands.iter().map(|c| c.get_name()).collect();
        assert!(names.contains(&"board"), "missing board noun");
        assert!(names.contains(&"task"), "missing task noun");
        assert!(names.contains(&"column"), "missing column noun");
        assert!(names.contains(&"tag"), "missing tag noun");
    }

    #[test]
    fn board_noun_has_expected_verbs() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let board = commands.iter().find(|c| c.get_name() == "board").unwrap();
        let verb_names: Vec<&str> = board.get_subcommands().map(|c| c.get_name()).collect();
        assert!(verb_names.contains(&"init"), "board missing init verb");
        assert!(verb_names.contains(&"get"), "board missing get verb");
        assert!(verb_names.contains(&"update"), "board missing update verb");
    }

    #[test]
    fn board_init_has_scoped_args() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let board = commands.iter().find(|c| c.get_name() == "board").unwrap();
        let init = board
            .get_subcommands()
            .find(|c| c.get_name() == "init")
            .unwrap();
        let arg_names: Vec<&str> = init.get_arguments().map(|a| a.get_id().as_str()).collect();

        assert!(arg_names.contains(&"name"), "init missing --name");
        // Should NOT have task-specific args (per-op scoping, not the global union)
        assert!(
            !arg_names.contains(&"title"),
            "init should not have --title"
        );
        assert!(
            !arg_names.contains(&"assignees"),
            "init should not have --assignees"
        );
    }

    #[test]
    fn board_init_name_is_required_but_global_name_optional_elsewhere() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let board = commands.iter().find(|c| c.get_name() == "board").unwrap();
        let init = board
            .get_subcommands()
            .find(|c| c.get_name() == "init")
            .unwrap();
        let name_arg = init
            .get_arguments()
            .find(|a| a.get_id().as_str() == "name")
            .unwrap();
        assert!(name_arg.is_required_set(), "init --name should be required");

        // update board has an optional `name`, so it must not be required there.
        let update = board
            .get_subcommands()
            .find(|c| c.get_name() == "update")
            .unwrap();
        let update_name = update
            .get_arguments()
            .find(|a| a.get_id().as_str() == "name")
            .unwrap();
        assert!(
            !update_name.is_required_set(),
            "update --name should be optional"
        );
    }

    #[test]
    fn extract_noun_verb_roundtrip() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let mut cmd = Command::new("mock");
        for subcmd in commands {
            cmd = cmd.subcommand(subcmd);
        }

        let matches = cmd
            .try_get_matches_from(["mock", "board", "init", "--name", "Test Board"])
            .unwrap();

        let args = extract_noun_verb_arguments(&matches, &schema).unwrap();
        assert_eq!(args.get("op").unwrap(), "init board");
        assert_eq!(args.get("name").unwrap(), "Test Board");
    }

    #[test]
    fn extract_task_add_with_optional_args() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let mut cmd = Command::new("mock");
        for subcmd in commands {
            cmd = cmd.subcommand(subcmd);
        }

        let matches = cmd
            .try_get_matches_from([
                "mock",
                "task",
                "add",
                "--title",
                "Fix bug",
                "--description",
                "Something broke",
            ])
            .unwrap();

        let args = extract_noun_verb_arguments(&matches, &schema).unwrap();
        assert_eq!(args.get("op").unwrap(), "add task");
        assert_eq!(args.get("title").unwrap(), "Fix bug");
        assert_eq!(args.get("description").unwrap(), "Something broke");
        // assignees not provided — should be absent
        assert!(args.get("assignees").is_none());
    }

    #[test]
    fn extract_task_add_collects_array_args() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let mut cmd = Command::new("mock");
        for subcmd in commands {
            cmd = cmd.subcommand(subcmd);
        }

        let matches = cmd
            .try_get_matches_from([
                "mock",
                "task",
                "add",
                "--title",
                "Fix bug",
                "--assignees",
                "alice",
                "--assignees",
                "bob",
            ])
            .unwrap();

        let args = extract_noun_verb_arguments(&matches, &schema).unwrap();
        let assignees = args.get("assignees").unwrap().as_array().unwrap();
        assert_eq!(assignees.len(), 2);
        assert_eq!(assignees[0], "alice");
        assert_eq!(assignees[1], "bob");
    }

    /// One `--flag '["a","b"]'` occurrence means one entry for each element.
    ///
    /// A shell argument carries one string, so a caller who means several
    /// entries writes them as a JSON array inside that one value. Joining them
    /// into a single entry silently invents a name nobody asked for.
    #[test]
    fn array_arg_expands_a_stringified_json_array() {
        let schema = mock_schema();
        let args = parse_and_extract(
            &schema,
            &[
                "mock",
                "task",
                "add",
                "--title",
                "Fix bug",
                "--assignees",
                r#"["alice","bob"]"#,
            ],
        );
        assert_eq!(args.get("assignees").unwrap(), &json!(["alice", "bob"]));
    }

    /// A scalar value is one entry, and a repeated flag beside a stringified
    /// array contributes its own entries in the order they were given.
    #[test]
    fn array_arg_mixes_scalars_and_stringified_arrays() {
        let schema = mock_schema();
        let args = parse_and_extract(
            &schema,
            &[
                "mock",
                "task",
                "add",
                "--title",
                "Fix bug",
                "--assignees",
                "alice",
                "--assignees",
                r#"["bob","carol"]"#,
            ],
        );
        assert_eq!(
            args.get("assignees").unwrap(),
            &json!(["alice", "bob", "carol"])
        );
    }

    /// A value that is not a JSON array of strings stays one entry, whole.
    ///
    /// Bracket characters are legal inside a ref, and a JSON array of numbers
    /// names no refs at all, so neither is expanded.
    #[test]
    fn array_arg_keeps_a_value_that_is_not_a_string_array() {
        let schema = mock_schema();
        for raw in ["[not json", "[1,2]"] {
            let args = parse_and_extract(
                &schema,
                &[
                    "mock",
                    "task",
                    "add",
                    "--title",
                    "Fix bug",
                    "--assignees",
                    raw,
                ],
            );
            assert_eq!(args.get("assignees").unwrap(), &json!([raw]));
        }
    }

    #[test]
    fn extract_missing_verb_returns_error() {
        let schema = mock_schema();
        let commands = build_commands_from_schema(&schema);

        let mut cmd = Command::new("mock")
            .subcommand_required(false)
            .allow_external_subcommands(true);
        for subcmd in commands {
            cmd = cmd.subcommand(subcmd);
        }

        // "board" noun without a verb — clap treats it as external subcommand
        let matches = cmd.try_get_matches_from(["mock", "board"]).unwrap();

        let result = extract_noun_verb_arguments(&matches, &schema);
        assert!(result.is_err());
    }

    /// Hand-built schema with one noun/verb carrying a single property.
    ///
    /// Produces the same `{ properties, x-operation-schemas, properties.op.enum }`
    /// shape `generate_mcp_schema` emits, but lets a test pin an arbitrary
    /// property `type` (e.g. a `["boolean", "null"]` union) that the real mock
    /// operations cannot express through [`crate::ParamType`].
    fn single_arg_schema(noun: &str, verb: &str, arg: &str, arg_schema: Value) -> Value {
        let op = format!("{} {}", verb, noun);
        json!({
            "type": "object",
            "properties": {
                "op": { "type": "string", "enum": [op] },
                arg: arg_schema,
            },
            "x-operation-schemas": [
                {
                    "title": op,
                    "description": format!("{} a {}", verb, noun),
                    "type": "object",
                    "properties": {
                        "op": { "const": op },
                        arg: arg_schema,
                    },
                    "required": ["op"],
                }
            ],
        })
    }

    /// Parse one invocation against the generated command tree and extract args.
    ///
    /// Thin wrapper over the shared [`super::test_support::parse_argv`] (which
    /// downstream CLIs also use) pinned to the `"mock"` root used here.
    fn parse_and_extract(schema: &Value, argv: &[&str]) -> serde_json::Map<String, Value> {
        super::test_support::parse_argv("mock", schema, argv)
    }

    #[test]
    fn nullable_boolean_roundtrips_true() {
        let schema = single_arg_schema(
            "task",
            "set",
            "ready",
            json!({ "type": ["boolean", "null"], "description": "Ready flag" }),
        );
        let args = parse_and_extract(&schema, &["mock", "task", "set", "--ready", "true"]);
        assert_eq!(args.get("op").unwrap(), "set task");
        assert_eq!(args.get("ready").unwrap(), &Value::Bool(true));
    }

    #[test]
    fn nullable_boolean_roundtrips_false() {
        let schema = single_arg_schema(
            "task",
            "set",
            "ready",
            json!({ "type": ["boolean", "null"], "description": "Ready flag" }),
        );
        let args = parse_and_extract(&schema, &["mock", "task", "set", "--ready", "false"]);
        assert_eq!(args.get("ready").unwrap(), &Value::Bool(false));
    }

    #[test]
    fn plain_boolean_flag_roundtrips() {
        let ops: Vec<&dyn Operation> = vec![&MockListTasks];
        let schema = generate_mcp_schema(&ops, SchemaConfig::new("Mock operations"));

        // Flag set -> true.
        let args = parse_and_extract(&schema, &["mock", "tasks", "list", "--ready"]);
        assert_eq!(args.get("ready").unwrap(), &Value::Bool(true));

        // Flag absent -> key omitted (booleans only emit when set).
        let absent = parse_and_extract(&schema, &["mock", "tasks", "list"]);
        assert!(absent.get("ready").is_none());
    }

    #[test]
    fn non_finite_float_is_rejected() {
        let schema = single_arg_schema(
            "calc",
            "run",
            "value",
            json!({ "type": "number", "description": "A number" }),
        );

        let commands = build_commands_from_schema(&schema);
        let mut cmd = Command::new("mock");
        for subcmd in commands {
            cmd = cmd.subcommand(subcmd);
        }
        let matches = cmd
            .try_get_matches_from(["mock", "calc", "run", "--value", "inf"])
            .unwrap();

        let result = extract_noun_verb_arguments(&matches, &schema);
        assert!(
            matches!(result, Err(CliExtractError::NonFiniteFloat { .. })),
            "expected NonFiniteFloat error, got {:?}",
            result
        );
    }

    #[test]
    fn finite_float_roundtrips() {
        let schema = single_arg_schema(
            "calc",
            "run",
            "value",
            json!({ "type": "number", "description": "A number" }),
        );
        let args = parse_and_extract(&schema, &["mock", "calc", "run", "--value", "1.5"]);
        assert_eq!(args.get("value").unwrap(), &json!(1.5));
    }
}
